# Generated by Django 5.0.6 on 2024-07-03 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chop_app', '0002_rename_company_course_student_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mark', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(5))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chop_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chop_app.student')),
            ],
        ),
    ]
