# Generated by Django 5.0.6 on 2024-07-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chop_app', '0003_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='mark',
        ),
    ]
